client_id = ""
client_secret = ""
redirect_uri = "http://localhost:8888/callback"  # has to be the same as in spotify app dev account
ping_url = ""
results_dir = "/app/data"
auth_cache_dir = "/app/auth-cache"
requests_timeout_seconds = 5
run_on_start = false # in addition to schedule it runs immediately on script start

[server]
host = "0.0.0.0"
port = 8888

[schedule]
cron = "0 1 * * *"  # Every day at 1 AM